### ISSUE TITLE
can't see devices

### ISSUE THREAD

**Issue by stardobas** [vwout/vera-tradfri#2]
sorry, I need some help, I have added tradfry bridge to vera and it is displayed in devices list but can't see the related devices like tradfry windows covering or switch tradfry..

**Comment by vwout** [comment]
Hi stardobas,

could you elaborate a bit on which system you used to installed the plugin on, what you did to install the plugin?

Have you followed the instructions in https://github.com/vwout/vera-tradfri#installation and https://github.com/vwout/vera-tradfri#limitations?

If so, does the list of variables for that that device contain a variable named 'Psk' with a value assigned?
When not, please follow the instructions in the link.
In case the Psk is listed, set the value Debug true and reload openLuup. Wait approx. 30 seconds and attach the console output (log) to this ticket - feel free to remove information not related to the Tradfri plugin.
